version: 2
updates:
  # GitHub Actions - weekly updates
  - package-ecosystem: github-actions
    target-branch: rootstock
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 10
    labels:
      - "dependencies"
      - "github_actions"
    groups:
      actions-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  # GitHub Actions - daily security updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    labels:
      - "dependencies"
      - "github_actions"
      - "security"
    groups:
      actions-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
          - major

  # Docker - weekly updates
  - package-ecosystem: docker
    target-branch: rootstock
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 10
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  # Docker - daily security updates
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    labels:
      - "dependencies"
      - "docker"
      - "security"
    groups:
      actions-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
          - major

  # NPM & Yarn - weekly updates
  - package-ecosystem: npm
    target-branch: rootstock
    directory: /
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "npm"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  # NPM & Yarn - daily security updates
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    labels:
      - "dependencies"
      - "npm"
      - "security"
    groups:
      npm-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
          - major
